config/routes.rb
# frozen_string_literal: true

Spina::Engine.routes.draw do
  namespace :admin, path: Spina.config.backend_path do
    namespace :conferences do
      namespace :accounts do
        resources :public_users, except: %i[show new]
      end
    end
  end
end

app/models/spina/admin/conferences/accounts/public_user.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Conferences
      module Accounts
        # User accounts
        class PublicUser < ApplicationRecord
          # Include default devise modules. Others available are:
          # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
          devise :database_authenticatable, :registerable,
                 :recoverable, :rememberable, :validatable,
                 :confirmable

          validates :first_name, presence: true
          validates :last_name, presence: true

          def full_name
            "#{first_name} #{last_name}"
          end
        end
      end
    end
  end
end

app/controllers/spina/admin/conferences/accounts/application_controller.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Conferences
      module Accounts
        # Custom controller for accounts plugin. Sets the layout and adds a flash type.
        class ApplicationController < AdminController
          helper ::Spina::Engine.routes.url_helpers

          add_flash_types :success

          layout :admin_layout, only: %i[new edit]

          before_action :set_locale

          private

          def admin_layout
            'spina/admin/admin'
          end

          def set_locale
            @locale = params[:locale] || I18n.default_locale
          end
        end
      end
    end
  end
end

app/controllers/spina/admin/conferences/accounts/public_users_controller.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Conferences
      module Accounts
        # Manages user accounts in Spina admin.
        class PublicUsersController < ApplicationController
          before_action :set_breadcrumb
          before_action :set_tabs, except: %i[index destroy]
          before_action :set_user, only: %i[edit update destroy]

          def index
            @users = PublicUser.all
          end

          def edit; end

          def update
            if @user.update(public_user_params)
              redirect_to admin_conferences_accounts_public_users_path, success: t('.saved')
            else
              render :edit
            end
          end

          def destroy
            @user.destroy
            respond_to do |format|
              format.html do
                redirect_to admin_conferences_accounts_public_users_path, success: t('.deleted')
              end
            end
          end

          private

          def public_user_params
            params.require(:public_user).permit(:email, :first_name, :last_name, :institution)
          end

          def set_breadcrumb
            add_breadcrumb PublicUser.model_name.human(count: :many), admin_conferences_accounts_public_users_path
          end

          def set_tabs
            @tabs = %w[details]
          end

          def set_user
            @user = PublicUser.find(params[:id])
            add_breadcrumb @user.full_name
          end
        end
      end
    end
  end
end

app/helpers/spina/admin/conferences/accounts/application_helper.rb
# frozen_string_literal: true

module Spina
  module Admin
    module Conferences
      module Accounts
        # Helper methods
        module ApplicationHelper
        end
      end
    end
  end
end

app/views/layouts/spina/admin/conferences/accounts/public_users.html.haml
- content_for :application do
  %header#header
    #header_actions
      = yield :header_actions

    = render partial: 'spina/admin/shared/breadcrumbs'

  = yield

= render template: 'layouts/spina/admin/admin'

app/views/spina/admin/conferences/accounts/public_users/_form.html.haml
- if @user.errors.any?
  - content_for :notifications do
    .notification.notification-danger.animated.fadeInRight
      = icon 'exclamation'
      .notification-message
        = t 'spina.notifications.alert'
        %small= @user.errors.full_messages.join('<br />').html_safe
      = link_to '#', data: { close_notification: true } do
        = icon 'cross'

= form_for [:admin_conferences_accounts, @user], html: {autocomplete: "off"} do |f|
  %header#header
    = render partial: 'spina/admin/shared/breadcrumbs'

    #header_actions
      %button.button.button-primary{ type: 'submit', style: 'margin-right: 0', data: { disable_with: t('spina.pages.saving') } }
        = icon 'check'
        = t '.save'

      .button{ style: 'margin-right: 0' }= link_to t('spina.cancel'), admin_conferences_accounts_public_users_path

    %nav#secondary.tabs
      %ul
        - @tabs.each_with_index do |tab, i|
          %li{ class: ('active' if i == 0) }
            = link_to t(".#{tab}"), "##{tab}"

  #details.tab-content.active= render 'form_details', f: f

app/views/spina/admin/conferences/accounts/public_users/_form_details.html.haml
.page-form
  .page-form-group
    .page-form-label
      = Spina::Admin::Conferences::Accounts::PublicUser.human_attribute_name :email
    .page-form-content
      = f.text_field :email
  .page-form-group
    .page-form-label
      = Spina::Admin::Conferences::Accounts::PublicUser.human_attribute_name :first_name
    .page-form-content
      = f.text_field :first_name
  .page-form-group
    .page-form-label
      = Spina::Admin::Conferences::Accounts::PublicUser.human_attribute_name :last_name
    .page-form-content
      = f.text_field :last_name
  .page-form-group
    .page-form-label
      = Spina::Admin::Conferences::Accounts::PublicUser.human_attribute_name :institution
    .page-form-content
      = f.text_field :institution

- unless @user.new_record?
  .pull-right= link_to t('spina.permanently_delete'), admin_conferences_accounts_public_user_path(@user), method: :delete, data: { confirm: t('.delete_confirmation', name: @user.full_name) }, class: 'button button-link button-danger'

app/views/spina/admin/conferences/accounts/public_users/_public_user.html.haml
%tr
  %td
    = link_to public_user.email, edit_admin_conferences_accounts_public_user_path(public_user)
  %td
    = public_user.full_name
  %td
    = public_user.institution
  %td.nowrap.align-right
    = link_to edit_admin_conferences_accounts_public_user_path(public_user), class: 'button button-link' do
      = icon 'pencil-outline'
      = t '.edit'

app/views/spina/admin/conferences/accounts/public_users/edit.html.haml
= render 'form'

app/views/spina/admin/conferences/accounts/public_users/index.html.haml
.well
  .table-container
    %table.table
      %thead
        %tr
          %th= Spina::Admin::Conferences::Accounts::PublicUser.human_attribute_name :email
          %th= t '.name'
          %th= Spina::Admin::Conferences::Accounts::PublicUser.human_attribute_name :institution
          %th

      %tbody
        = render @users, message: t('.empty')

app/views/spina/admin/hooks/conferences/accounts/_head.html.haml
= stylesheet_link_tag 'spina/admin/conferences/accounts/application', media: 'all', data: { turbolinks_track: true }
= javascript_include_tag 'spina/admin/conferences/accounts/application'

app/views/spina/admin/hooks/conferences/accounts/_primary_navigation.html.haml
%li{ class: ('active' if %w[public_users].include? controller_name) }
  = link_to admin_conferences_accounts_public_users_path do
    = icon 'users-outline'
    = t 'spina.admin.conferences.accounts.navigation_title'
    = icon 'caret-right'

    %ul
      %li{ class: ('active' if %w[public_users].include? controller_name) }
        = link_to t('spina.admin.conferences.accounts.subnavigation_title'), admin_conferences_accounts_public_users_path